default:
    before:
        - composer.json
        - LICENSE
        - README.md
        - .travis.yml
        - .scrutinizer.yml
install:
    before:
        - composer/install
update:
    before:
        - start/update
        - composer/update
fix:
    before: php-cs-fixer
test:
    before:
        - install
        - phpunit
build:
    before:
        - fix
        - test

readme:
    badges:
        packagist.stable:
        packagist.downloads:
        travis.build:
        scrutinizer.coverage:
        scrutinizer.quality:
        versioneye.dependencies:

php-cs-fixer:
    level: psr2

phpunit:
    colors:         always
    coverageText:   true
    coverageClover: true

vcsignore:
    coverage.clover: phpunit generated files

codeception:
    before:
        - generate/mkdir tests
        - generate/once  tests/_bootstrap

codeception.yml:
    coverage:
        enable: true

.travis.yml:
    language: php
    php:
        - 5.5
        - 5.6
        - 7
        - hhvm
    matrix:
        allow_failures:
            - php: hhvm
            - php: 5.5
    cache:
        directories:
            - $HOME/.composer/cache
    before_install:
        - composer self-update
        - composer --version

travis:
    after_script:
        - scrutinizer/upload-coverage

.scrutinizer.yml:
    checks:
        php:
            code_rating: true
            duplication: true
    tools:
        php_code_coverage:
            enabled: true
        external_code_coverage:
            timeout: 600
