package:
    name:           hidev-config-php
    namespace:      hiqdev\hidev\config\php
    label:          HiDevConfigPHP
    title:          HiQDev's hidev config for PHP projects
    type:           yii2-extension
    keywords:       hiqdev, hidev, config, php
    year:           2015

require:
    hiqdev/hidev-config:        "*@dev"
    hiqdev/hidev-config-php:    "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
    hiqdev/hidev-codeception:   "*@dev"
