package:
    type:           yii2-extension
    name:           hidev-php
    namespace:      hidev\php
    headline:       HiDev PHP
    title:          HiDev config for PHP projects
    keywords:       hidev, config, php
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin provides basic HiDev configuration for PHP projects.

        Provides:
        - standart: .gitignore, LICENSE, README.md, CHANGELOG.md
        - composer.json
        - PHP-CS-Fixer
        - Codeception
        - Travis CI (in progress)
        - Scrutinizer (in progress)

include:
    - src/config.yml

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-hiqdev:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-travis-ci:     "*@dev"
    hiqdev/hidev-codeception:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
