default:
    before:
        - composer
        - LICENSE
        - README.md
        - CHANGELOG.md
        - .travis.yml
other:
        - .scrutinizer.yml
fix:
    before: php-cs-fixer
test:
    before: phpunit
build:
    before:
        - fix
        - test

readme:
    badges:
        packagist.stable:
        packagist.downloads:
        travis.build:
        scrutinizer.coverage:
        scrutinizer.quality:
        versioneye.dependencies:

php-cs-fixer:
    level: psr2

phpunit:
    colors:         always
    coverageText:   true
    coverageClover: true

vcsignore:
    coverage.clover: phpunit generated files

codeception:
    before:
        - generate/mkdir tests
        - generate/once  tests/_bootstrap

codeception.yml:
    coverage:
        enable: true

.travis.yml:
    language: php

    php:
        - 5.5
        - 5.6
        - 7
        - hhvm

    matrix:
        allow_failures:
            - php: hhvm

    cache:
        directories:
            - $HOME/.composer/cache

travis:
    after_script:
        coverage: scrutinizer/upload-coverage

.scrutinizer.yml:
    checks:
        php:
            code_rating: true
            duplication: true
    tools:
        php_code_coverage:
            enabled: true
        external_code_coverage:
            timeout: 600
